version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "AWSResumeVisitorCounter"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-datxuc2d3nka"
s3_prefix = "AWSResumeVisitorCounter"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
