AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AWS Resume - Visitor Counter

Resources:
  VisitorCounterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: Lambda/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        visitFunction:
          Type: Api
          Properties:
            Path: /count
            Method: get
      Environment:
        Variables: 
          databaseName : !Ref VisitCount
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref VisitCount

  VisitCount:
    Type: AWS::Serverless::SimpleTable
    
Outputs:
  visitFunctionApi:
    Description: "API Gateway endpoint URL for Prod stage for Visitor Counter function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/count/"